#!/bin/bash

function sum() {
  local input
  if [[ "${#}" -gt 0 ]]; then
    input=${@}
  else
    input=$( cat )
  fi
  {
    echo -n "0";
    for x in ${input}; do
      echo -n " + ${x}"
    done;
    echo;
  } | bc -l
}

while read LINE; do
  #echo "Processing: ${LINE}"
  newLINE=$(
    sed -e 's/one/o1e/g' \
        -e 's/two/t2o/g' \
        -e 's/three/t3e/g' \
        -e 's/four/f4r/g' \
        -e 's/five/f5e/g' \
        -e 's/six/s6x/g' \
        -e 's/seven/s7n/g' \
        -e 's/eight/e8t/g' \
        -e 's/nine/n9e/g' <<<"${LINE}" )
  #echo "Preprocessed: ${newLINE}"
  grep -Po '\d' <<<"${newLINE}" | # Only print the digits, one per line
    sed -n '1p;$p' | # Print the first line.  Print the last ($) line.
    tr -d '\n' # Remove the newline characters
  echo # Add 1 newline character
done < $1 | sum

