#!/bin/bash

function sum() {
  local input
  if [[ "${#}" -gt 0 ]]; then
    input=${@}
  else
    input=$( cat )
  fi
  {
    echo -n "0";
    for x in ${input}; do
      echo -n " + ${x}"
    done;
    echo;
  } | bc -l
}


lst=$( 
  sum=0
  while read LINE; do
    echo "RSum: ${sum}"  >&2
    echo "Read: ${LINE}" >&2
  
    if [[ "${LINE}" != "" ]]; then
      sum=$((sum+LINE))
      continue
    fi
    echo "Total: ${sum}" >&2
  
    echo "${sum}"
    sum=0
  done < "${1}"
)

echo "Fattest 3:"
echo "${lst}" | sort -n | tail -n 3

echo -n "Total calories: "
echo "${lst}" | sort -n | tail -n 3 | sum


