#!/bin/bash

inFile="${1}"

# Split input file into one file per passport
rm -f parts/out*.txt
cat "${inFile}" | 
  awk '/^\s*$/{n++}
    {print >"parts/out"n".txt"}
    END {print n}'


function sum() {
  local input
  if [[ "${#}" -gt 0 ]]; then
    input=${@}
  else
    input=$( cat )
  fi
  {
    echo -n "0";
    for x in ${input}; do
      echo -n " + ${x}"
    done;
    echo;
  } | bc -l
}


for group in parts/*; do
  while read -n 1 char; do
    echo "${char}"
  done < "${group}" |
    sort -u |
    grep -vP '^\s*$' | wc -l
done | sum


