#!/bin/bash

inFile="${1}"

#
# Helper functions
#

function debug() {
  local ts=$( date +"%F %T.%N" )
  echo "${ts}: ${@}" >&2
}

function sum() {
  local input
  if [[ "${#}" -gt 0 ]]; then
    input=${@}
  else
    input=$( cat )
  fi
  {
    echo -n "0";
    for x in ${input}; do
      echo -n " + ${x}"
    done;
    echo;
  } | bc -l
}

function printPocket() {
  local cubeState
  for w in $( seq ${wMin} ${wMax} ); do
    for z in $( seq ${zMin} ${zMax} ); do
      echo
      echo ">>> Z=${z}, W=${w}"
      for y in $( seq ${yMin} ${yMax} ); do
        echo -ne "Y=${y}:\t"
        for x in $( seq ${xMin} ${xMax} ); do
          cubeState=${pocketState[$x,$y,$z,$w]}
          echo -n "${cubeState:-0}"
        done
        echo
      done
    done
  done
}

function getNeighbours() {
  local xPos="${1}"
  local yPos="${2}"
  local zPos="${3}"
  local wPos="${4}"

  for x in $(seq $((xPos-1)) $((xPos+1))); do
    for y in $(seq $((yPos-1)) $((yPos+1))); do
      for z in $(seq $((zPos-1)) $((zPos+1))); do
        for w in $(seq $((wPos-1)) $((wPos+1))); do
          # I'm not my own neighbour:
          if [[ "${y}" -eq "${yPos}" ]] &&
             [[ "${x}" -eq "${xPos}" ]] &&
             [[ "${z}" -eq "${zPos}" ]] &&
             [[ "${w}" -eq "${wPos}" ]]; then
            continue
          fi
          echo "${x} ${y} ${z} ${w}"
        done
      done
    done
  done
}

function isActive() {
  local xPos="${1}"
  local yPos="${2}"
  local zPos="${3}"
  local wPos="${4}"

  # All cubes outside our purview are inactive:
  #[[ ${xPos} -lt ${xMin} ]] && return 1
  #[[ ${yPos} -lt ${yMin} ]] && return 1
  #[[ ${zPos} -lt ${zMin} ]] && return 1
  #[[ ${xPos} -gt ${xMax} ]] && return 1
  #[[ ${yPos} -gt ${yMax} ]] && return 1
  #[[ ${zPos} -gt ${zMax} ]] && return 1
  [[ -z "${pocketState[${xPos},${yPos},${zPos},${wPos}]}" ]] && return 1

  # If it's inactive, also return 1 (false/fail)
  [[ ${pocketState[${xPos},${yPos},${zPos},${wPos}]} -eq 0 ]] && return 1

  # All invalid exhausted - return 0 (true/success)
  return 0
}

function countActiveNeighbours() {
  local xPos="${1}"
  local yPos="${2}"
  local zPos="${3}"
  local wPos="${4}"
  
  local neighbourCoords="$( getNeighbours ${xPos} ${yPos} ${zPos} ${wPos} )"
  # Taking advantage of 0=inactive, 1=active
  while read x y z w; do
    echo "${pocketState[${x},${y},${z},${w}]}"
  done <<<"${neighbourCoords}" | sum
}


function getNextState() {
  local xPos="${1}"
  local yPos="${2}"
  local zPos="${3}"
  local wPos="${4}"
  local activeNeighbours=$(countActiveNeighbours ${xPos} ${yPos} ${zPos} ${wPos})

  if isActive ${xPos} ${yPos} ${zPos} ${wPos}; then
    # If a cube is active and exactly 2 or 3 of its neighbors are also active, the cube remains active. Otherwise, the cube becomes inactive.
    if [[ ${activeNeighbours} -eq 2 ]] ||
       [[ ${activeNeighbours} -eq 3 ]]; then
      echo 1
    else
      echo 0
    fi
  else
    # If a cube is inactive but exactly 3 of its neighbors are active, the cube becomes active. Otherwise, the cube remains inactive.
    if [[ ${activeNeighbours} -eq 3 ]]; then
      echo 1
    else
      echo 0
    fi
  fi
}

function changeState() {
  debug "Updating Pocket state."
  debug "New dimensions:"
  debug "X: ${xMin} to ${xMax}"
  debug "Y: ${yMin} to ${yMax}"
  debug "Z: ${zMin} to ${zMax}"
  debug "W: ${wMin} to ${wMax}"
  for w in $(seq ${wMin} ${wMax}); do
    for z in $(seq ${zMin} ${zMax}); do
      for y in $(seq ${yMin} ${yMax}); do
        for x in $(seq ${xMin} ${xMax}); do
          pocketState[${x},${y},${z},${w}]=${nextPocketState[${x},${y},${z},${w}]}
        done
      done
    done
  done
}

function trimBoundaries() {
  local shrinkable

  # Attempt to narrow X coords:
  shrinkable="True"
  for y in $(seq ${yMin} ${yMax}); do
    for z in $(seq ${zMin} ${zMax}); do
      for w in $(seq ${wMin} ${wMax}); do
        if isActive ${xMin} ${y} ${z} ${w}; then
          shrinkable="False"
          break 3
        fi
      done
    done
  done
  if [[ "${shrinkable}" == "True" ]]; then
    debug "xMin layer ${xMin} is *all* inactive - removing that whole layer"
    xMin=$(( xMin+1 ))
  fi
  shrinkable="True"
  for y in $(seq ${yMin} ${yMax}); do
    for z in $(seq ${zMin} ${zMax}); do
      for w in $(seq ${wMin} ${wMax}); do
        if isActive ${xMax} ${y} ${z} ${w}; then
          shrinkable="False"
          break 3
        fi
      done
    done
  done
  if [[ "${shrinkable}" == "True" ]]; then
    debug "xMax layer ${xMax} is *all* inactive - removing that whole layer"
    xMax=$(( xMax-1 ))
  fi

  # Attempt to narrow Y coords:
  shrinkable="True"
  for x in $(seq ${xMin} ${xMax}); do
    for z in $(seq ${zMin} ${zMax}); do
      for w in $(seq ${wMin} ${wMax}); do
        if isActive ${x} ${yMin} ${z} ${w}; then
          shrinkable="False"
          break 3
        fi
      done
    done
  done
  if [[ "${shrinkable}" == "True" ]]; then
    debug "Y layer ${yMin} is *all* inactive - removing that whole layer"
    yMin=$(( yMin+1 ))
  fi
  shrinkable="True"
  for x in $(seq ${xMin} ${xMax}); do
    for z in $(seq ${zMin} ${zMax}); do
      for w in $(seq ${wMin} ${wMax}); do
        if isActive ${x} ${yMax} ${z} ${w}; then
          shrinkable="False"
          break 3
        fi
      done
    done 
  done
  if [[ "${shrinkable}" == "True" ]]; then
    debug "Y layer ${yMax} is *all* inactive - removing that whole layer"
    yMax=$(( yMax-1 ))
  fi

  # Attempt to narrow Z coords:
  shrinkable="True"
  for x in $(seq ${xMin} ${xMax}); do
    for y in $(seq ${yMin} ${yMax}); do
      for w in $(seq ${wMin} ${wMax}); do
        if isActive ${x} ${y} ${zMin} ${w}; then
          shrinkable="False"
          break 3
        fi
      done
    done
  done
  if [[ "${shrinkable}" == "True" ]]; then
    debug "zMin layer ${zMin} is *all* inactive - removing that whole layer"
    zMin=$(( zMin+1 ))
  fi
  shrinkable="True"
  for x in $(seq ${xMin} ${xMax}); do
    for y in $(seq ${yMin} ${yMax}); do
      for w in $(seq ${wMin} ${wMax}); do
        if isActive ${x} ${y} ${zMax} ${w}; then
          shrinkable="False"
          break 3
        fi
      done
    done
  done
  if [[ "${shrinkable}" == "True" ]]; then
    debug "zMax layer ${zMax} is *all* inactive - removing that whole layer"
    zMax=$(( zMax-1 ))
  fi

  # Attempt to narrow W coords:
  shrinkable="True"
  for x in $(seq ${xMin} ${xMax}); do
    for y in $(seq ${yMin} ${yMax}); do
      for z in $(seq ${zMin} ${zMax}); do
        if isActive ${x} ${y} ${z} ${wMin}; then
          shrinkable="False"
          break 3
        fi
      done
    done
  done
  if [[ "${shrinkable}" == "True" ]]; then
    debug "W layer ${wMin} is *all* inactive - removing that whole layer"
    wMin=$(( wMin+1 ))
  fi
  shrinkable="True"
  for x in $(seq ${xMin} ${xMax}); do
    for y in $(seq ${yMin} ${yMax}); do
      for z in $(seq ${zMin} ${zMax}); do
        if isActive ${x} ${y} ${z} ${wMax}; then
          shrinkable="False"
          break 3
        fi
      done
    done
  done
  if [[ "${shrinkable}" == "True" ]]; then
    debug "W layer ${wMax} is *all* inactive - removing that whole layer"
    wMax=$(( wMax-1 ))
  fi
}


#----------------#
#---Core logic---#
#----------------#

# This thing grows dynamically, so we need to track our coordinate bounds:
xMin=0
xMax=$(( $( head -n 1 "${inFile}" | tr -d '\n' | wc -c ) - 1 ))
yMin=0
wMin=0
yMax=$(( $( wc -l < "${inFile}" ) - 1 ))
zMin=0
zMax=0
wMax=0

declare -A pocketState
xPos=0
yPos=0
zPos=0
wPos=0
while read LINE; do
  # 0 = Inactive
  # 1 = Active
  xPos=0
  while read -n1 char; do
    if [[ "${char}" == "#" ]]; then
      pocketState[${xPos},${yPos},${zPos},${wPos}]=1
    else
      pocketState[${xPos},${yPos},${zPos},${wPos}]=0
    fi
    xPos=$((xPos+1))
  done <<<"${LINE}"
  yPos=$((yPos+1))
done < <( cat "${inFile}" )

debug "Start state:"
printPocket

declare -A nextPocketState
for iteration in {1..6}; do
  #echo "Bounds:"
  #echo "X: ${xMin} to ${xMax}"
  #echo "Y: ${yMin} to ${yMax}"
  #echo "Z: ${zMin} to ${zMax}"
  #echo "W: ${wMin} to ${wMax}"

  trimBoundaries

  # Decrement min
  xMin=$((xMin-1))
  yMin=$((yMin-1))
  zMin=$((zMin-1))
  wMin=$((wMin-1))
  # Increment max
  xMax=$((xMax+1))
  yMax=$((yMax+1))
  zMax=$((zMax+1))
  wMax=$((wMax+1))

  # Have each cube figure out its next state
  # Note: This could be parallelized
  for w in $(seq ${wMin} ${wMax}); do
    for z in $(seq ${zMin} ${zMax}); do
      for y in $(seq ${yMin} ${yMax}); do
        for x in $(seq ${xMin} ${xMax}); do
          nextState=$( getNextState ${x} ${y} ${z} ${w} )
          nextPocketState[${x},${y},${z},${w}]=${nextState}
        done
      done
    done
  done

  # Copy nextPocketState into pocketState
  changeState

  printPocket
  debug "After ${iteration} iterations: $(echo "${pocketState[@]}" | sum)"
  echo "${pocketState[@]}" | sum
done


# Count the actives:
#printPocket
echo "Total active cubes:"
echo "${pocketState[@]}" | sum


