#!/bin/bash

max=0
sum=0
while read LINE; do
  echo "RSum: ${sum}"
  echo "Read: ${LINE}"

  if [[ "${LINE}" != "" ]]; then
    sum=$((sum+LINE))
    echo
    continue
  fi

  echo "Total: ${sum}"
  if [[ ${sum} -gt ${max} ]]; then
    max=${sum}
  fi
  sum=0
  echo
done < "${1}"

echo "${max}"
