#!/bin/bash

while read LINE; do
  grep -Po '\d' <<<"${LINE}" | # Only print the digits, one per line
    sed -n '1p;$p' | # Print the first line.  Print the last ($) line.
    tr -d '\n' # Remove the newline characters
  echo # Add 1 newline character
done < $1 | awk '{s+=$1} END {print s}'

