#!/bin/bash

if [[ ${#} -ne 1 ]]; then
  echo "Missing argument: Input file" >&2
  exit 1
fi

INFILE="${1}"
if ! [[ -r "${INFILE}" ]]; then
  echo "Unable to read input file: ${INFILE}" >&2
  exit 1
fi

# Define some math libraries:
. ../../math.bash


powerSum=0
while read LINE; do
  minred=$( grep -Po '\d+\s+red' <<<"${LINE}" | max )
  mingrn=$( grep -Po '\d+\s+green' <<<"${LINE}" | max )
  minblu=$( grep -Po '\d+\s+blue' <<<"${LINE}" | max )
  sum=$((sum + minred*mingrn*minblu))
done < "${INFILE}"

echo "Power Sum: ${sum}"
